### ISSUE TITLE
need installation instructions

### ISSUE THREAD

**Issue by martinthurn-LFT** [TheSuspiciousWombat/SusColors-emacs#2]
I've never used Melpa before.  Could you add a line or two to the README.md that says EXACTLY how to install suscolors?  TIA

**Comment by martinthurn-LFT** [comment]
Well...  I see how this might not be appropriate for your README.  The melpa.org website should have this info, but it doesn't!

**Comment by TheSuspiciousWombat** [comment]
You need to add the Melpa repo to your emacs, https://melpa.org/#/getting-started.
After that one way would be to use "M-x list-packages" and mark suscolors for instalation (I) and confirm with (x).

**Comment by martinthurn-LFT** [comment]
Thanks.  Unfortunately, my Emacs 24.5.1 gives error

if: Archive location https://melpa.org/packages/ is not an absolute file name

**Comment by TheSuspiciousWombat** [comment]
Could you post your .emacs? or the part you added?

**Comment by martinthurn-LFT** [comment]
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(add-to-list 'package-archives
             '("marmalade" . "https://marmalade-repo.org/packages/"))
; (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))
(package-initialize)

; The melpa-stable URL gives a "failed to download" error so I commented it out

**Comment by TheSuspiciousWombat** [comment]
At what point the error occures?
You could try "M-x package-install" also.
Unfortunately i cant reproduce your issue so this seems to be a problem on your or the melpa side so you might be better off to ask them.
But feel free to answer my question as i would like to try to help you.

**Comment by martinthurn-LFT** [comment]
That error comes e.g. during M-x package-install after I type the package name and press return.

**Comment by TheSuspiciousWombat** [comment]
I added instructions, maybe one of the other 2 works for you for now?

**Comment by martinthurn-LFT** [comment]
The "manual" method works.  Thank you!
